// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:movie_browser/features/movies/data/models/movie_details_model.dart';
import 'package:movie_browser/features/movies/data/models/movie_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MovieDetailsModelAdapter());
    registerAdapter(MovieModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MovieDetailsModelAdapter());
    registerAdapter(MovieModelAdapter());
  }
}
